@startuml

alt Обозначения
Host <-- Converter : Подпись на событие
Host <- Converter : Вызов события
Host X- Converter : Отписка от события
end

alt Подготовка к инициализации соединения
Host <-- Converter : unbusy <parent id>
Host <-- Converter: <confirm issue> <host_id>
Host <-- Converter : timeout
Host <-- Converter : close
Host <-- Converter : error

Converter <-- Device : unbusy <parent id>
Converter <-- Device : <confirm issue> <converter_id>
Converter <-- Device : timeout
Converter <-- Device : close
Converter <-- Device : error
Host -> Converter : unbusy ->id <-converter_id
Host --> Converter : set_issue converter_id
Device <- Converter : unbusy ->id  <-device_id
Device <-- Converter : set_issue device_id
Device -> Converter : set_issue device_id issue
Converter -> Host : set_issue device_id issue

Host -> Converter: <confirm issue>  <issue_id>  <id>
Host --> Converter: <sconfirm issue>  <issue_id>  <id>


Converter -> Device: <confirm issue>  <issue_id>  <id>
Converter --> Device: <sconfirm issue>  <issue_id>  <id>
Converter <- Device: <sconfirm issue>  <issue_id>  <id>
activate Device

Device -> Device: <confirm issue>  <issue_id>  <id>
 activate Converter

Host <- Converter: <sconfirm issue>  <issue_id>  <id>
Host x- Converter: <sconfirm issue>  <issue_id>  <id>
activate Host


end

alt Обмен перед началом опроса
Converter <- Device: send pack
Converter -x Device: confirm issue
Host <- Converter: send pack
Host x- Converter: confirm issue
Converter -x Device: set issue
Host -x Converter: set issue
end
alt Опрос
Host -> Converter: parse pack
Converter -> Device: parse pack
Converter <- Device: send pack
Host <- Converter: send pack
Host -> Converter: parse pack
Converter -> Device: parse pack
end
alt Завершение опроса
Converter x- Device: done
deactivate Converter
Host x- Converter: done
deactivate Host
end
alt Закрытие процесса

Host -x Converter: timeout
Host -x Converter: close
Host -x Converter: error

Converter -x Device: timeout close
Converter -x Device: close
Converter -x Device: error





end
Host -> Converter : unbusy
Converter -> Device : unbusy
@enduml
'https://www.planttext.com/