module.exports = {
    PARAMETER_ENEMGY_TARIF_1 : 'PARAMETER_ENEMGY_TARIF_1' ,
    PARAMETER_ENEMGY_TARIF_2 : 'PARAMETER_ENEMGY_TARIF_2' ,
    PARAMETER_ENEMGY_TARIF_SUM : 'PARAMETER_ENEMGY_TARIF_SUM' ,
}