module.exports = {
    CMD_TEST_MODE_CLOSE : 'CMD_TEST_MODE_CLOSE',
    CMD_TEST_MODE_TIMEOUT : 'CMD_TEST_MODE_TIMEOUT',
    CMD_TEST_MODE_ERROR : 'CMD_TEST_MODE_ERROR',
    GET_ACTUAL_DATA : 'GET_ACTUAL_DATA',
    CLOSE : 'CLOSE',
    SET_PARAM_CONNECT : 'SET_PARAM_CONNECT',
    CONNECT : 'CONNECT',
}